[0001].[2021.04.03.01.33.00.054161].SRV1.INF:Main.py.<module>.307:Main Program Started
[0002].[2021.04.03.01.33.00.054662].SRV1.ERR:Main.py.<module>.310:Artificial Error Message for testing purpose
[0003].[2021.04.03.01.33.00.055162].SRV1.INF:Main.py.<module>.311:Command Line iniFileName=default.ini
[0004].[2021.04.03.01.33.00.055662].SRV1.INF:Main.py.<module>.313:Command Line VerboseMode=None
[0005].[2021.04.03.01.33.00.056163].SRV1.INF:Main.py.<module>.316:AppSpoManager.DebugVerboseModeOn=True
[0006].[2021.04.03.01.33.00.056663].SRV1.INF:Main.py.<module>.317:AppSpoManager.DebugInfoMessages=True
[0007].[2021.04.03.01.33.00.057163].SRV1.INF:Main.py.<module>.318:AppSpoManager.DebugErrorMessages=True
[0008].[2021.04.03.01.33.00.057663].SRV1.INF:Main.py.<module>.319:AppSpoManager.DebugTargetConsole=False
[0009].[2021.04.03.01.33.00.058164].SRV1.INF:Main.py.<module>.320:AppSpoManager.DebugTargetFile=True
[0010].[2021.04.03.01.33.00.058664].SRV1.INF:Main.py.<module>.321:AppSpoManager.DebugTargetFilePath=Debugs\Debug1
[0011].[2021.04.03.01.33.00.059164].SRV1.INF:Main.py.<module>.322:AppSpoManager.DebugLinesPerFile=1000
[0012].[2021.04.03.01.33.00.059665].SRV1.INF:Main.py.<module>.323:AppSpoManager.AppRunFolder=c:\Apps\PythonTry1
[0013].[2021.04.03.01.33.00.060165].SRV1.INF:Main.py.<module>.346:ModuleFileNameOnly=Main.py
[0014].[2021.04.03.01.33.00.060665].SRV1.INF:Main.py.<module>.354:File=c:\Apps\PythonTry1\Main.py
[0015].[2021.04.03.01.33.00.061166].SRV1.INF:Main.py.<module>.355:FileDirName=c:\Apps\PythonTry1
[0016].[2021.04.03.01.33.00.061666].SRV1.INF:Main.py.<module>.356:FileAbsPath=c:\Apps\PythonTry1\Main.py
[0017].[2021.04.03.01.33.00.062167].SRV1.INF:Main.py.<module>.359:ModuleName1=__main__
[0018].[2021.04.03.01.33.00.062667].SRV1.INF:Main.py.<module>.360:ModuleName2=Main
[0019].[2021.04.03.01.33.00.063167].SRV1.INF:Main.py.<module>.369:Main Program Started
[0020].[2021.04.03.01.33.00.063668].SRV1.INF:Main.py.<module>.370:Python Executable Path=C:\Program Files\Python39\python.exe
[0021].[2021.04.03.01.33.00.064168].SRV1.INF:Main.py.<module>.371:Python Interpreter Version=3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
[0022].[2021.04.03.01.33.00.064668].SRV1.INF:Main.py.<module>.374:Sys.Path=['c:\\Apps\\PythonTry1', 'C:\\Program Files\\Python39\\python39.zip', 'C:\\Program Files\\Python39\\DLLs', 'C:\\Program Files\\Python39\\lib', 'C:\\Program Files\\Python39', 'C:\\Users\\user2\\AppData\\Roaming\\Python\\Python39\\site-packages', 'C:\\Program Files\\Python39\\lib\\site-packages']
[0023].[2021.04.03.01.33.00.093187].SRV1.INF:Main.py.<module>.421:Showing MainWindow
[0024].[2021.04.03.01.33.01.631495].SRV1.INF:Main.py.actionDebugTest1Handler.154:192.168.0.1, KAT1.ODA1, KORÝDOR DUVAR
192.168.0.2, KAT2.ODA2, TAVAN HOPARLÖR
192.168.0.3, KAT2.ODA2, KAPI_ÖNÜ_ANANS
[0025].[2021.04.03.01.33.01.633499].SRV1.INF:Main.py.actionDebugTest1Handler.157:Node[0]=[192.168.0.1, KAT1.ODA1, KORÝDOR DUVAR]
[0026].[2021.04.03.01.33.01.634499].SRV1.INF:Main.py.actionDebugTest1Handler.157:Node[1]=[192.168.0.2, KAT2.ODA2, TAVAN HOPARLÖR]
[0027].[2021.04.03.01.33.01.635500].SRV1.INF:Main.py.actionDebugTest1Handler.157:Node[2]=[192.168.0.3, KAT2.ODA2, KAPI_ÖNÜ_ANANS]
