[0001].[2021.04.02.23.32.52.400787].SRV1.INF:Main.py.<module>.283:Main Program Started
[0002].[2021.04.02.23.32.52.401786].SRV1.ERR:Main.py.<module>.286:Artificial Error Message for testing purpose
[0003].[2021.04.02.23.32.52.402629].SRV1.INF:Main.py.<module>.287:Command Line iniFileName=default.ini
[0004].[2021.04.02.23.32.52.403420].SRV1.INF:Main.py.<module>.289:Command Line VerboseMode=None
[0005].[2021.04.02.23.32.52.404422].SRV1.INF:Main.py.<module>.292:AppSpoManager.DebugVerboseModeOn=True
[0006].[2021.04.02.23.32.52.404422].SRV1.INF:Main.py.<module>.293:AppSpoManager.DebugInfoMessages=True
[0007].[2021.04.02.23.32.52.405422].SRV1.INF:Main.py.<module>.294:AppSpoManager.DebugErrorMessages=True
[0008].[2021.04.02.23.32.52.405422].SRV1.INF:Main.py.<module>.295:AppSpoManager.DebugTargetConsole=True
[0009].[2021.04.02.23.32.52.406423].SRV1.INF:Main.py.<module>.296:AppSpoManager.DebugTargetFile=True
[0010].[2021.04.02.23.32.52.407423].SRV1.INF:Main.py.<module>.297:AppSpoManager.DebugTargetFilePath=Debugs\Debug1
[0011].[2021.04.02.23.32.52.407423].SRV1.INF:Main.py.<module>.298:AppSpoManager.DebugLinesPerFile=1000
[0012].[2021.04.02.23.32.52.408424].SRV1.INF:Main.py.<module>.299:AppSpoManager.AppRunFolder=c:\Apps\PythonTry1
[0013].[2021.04.02.23.32.52.409425].SRV1.INF:Main.py.<module>.322:ModuleFileNameOnly=Main.py
[0014].[2021.04.02.23.32.52.409606].SRV1.INF:Main.py.<module>.330:File=c:\Apps\PythonTry1\Main.py
[0015].[2021.04.02.23.32.52.410608].SRV1.INF:Main.py.<module>.331:FileDirName=c:\Apps\PythonTry1
[0016].[2021.04.02.23.32.52.410608].SRV1.INF:Main.py.<module>.332:FileAbsPath=c:\Apps\PythonTry1\Main.py
[0017].[2021.04.02.23.32.52.411608].SRV1.INF:Main.py.<module>.335:ModuleName1=__main__
[0018].[2021.04.02.23.32.52.411608].SRV1.INF:Main.py.<module>.336:ModuleName2=Main
[0019].[2021.04.02.23.32.52.412610].SRV1.INF:Main.py.<module>.345:Main Program Started
[0020].[2021.04.02.23.32.52.413610].SRV1.INF:Main.py.<module>.346:Python Executable Path=C:\Program Files\Python39\python.exe
[0021].[2021.04.02.23.32.52.413610].SRV1.INF:Main.py.<module>.347:Python Interpreter Version=3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
[0022].[2021.04.02.23.32.52.414610].SRV1.INF:Main.py.<module>.350:Sys.Path=['c:\\Apps\\PythonTry1', 'C:\\Program Files\\Python39\\python39.zip', 'C:\\Program Files\\Python39\\DLLs', 'C:\\Program Files\\Python39\\lib', 'C:\\Program Files\\Python39', 'C:\\Users\\user2\\AppData\\Roaming\\Python\\Python39\\site-packages', 'C:\\Program Files\\Python39\\lib\\site-packages']
[0023].[2021.04.02.23.32.52.690280].SRV1.INF:Main.py.<module>.424:Showing MainWindow
[0024].[2021.04.02.23.32.54.834055].SRV1.INF:Main.py.actionExitHandler.173:User wanted to exit
