[0001].[2021.04.03.01.17.14.850628].SRV1.INF:Main.py.<module>.300:Main Program Started
[0002].[2021.04.03.01.17.14.851628].SRV1.ERR:Main.py.<module>.303:Artificial Error Message for testing purpose
[0003].[2021.04.03.01.17.14.852129].SRV1.INF:Main.py.<module>.304:Command Line iniFileName=default.ini
[0004].[2021.04.03.01.17.14.852629].SRV1.INF:Main.py.<module>.306:Command Line VerboseMode=None
[0005].[2021.04.03.01.17.14.853129].SRV1.INF:Main.py.<module>.309:AppSpoManager.DebugVerboseModeOn=True
[0006].[2021.04.03.01.17.14.853630].SRV1.INF:Main.py.<module>.310:AppSpoManager.DebugInfoMessages=True
[0007].[2021.04.03.01.17.14.854130].SRV1.INF:Main.py.<module>.311:AppSpoManager.DebugErrorMessages=True
[0008].[2021.04.03.01.17.14.854630].SRV1.INF:Main.py.<module>.312:AppSpoManager.DebugTargetConsole=False
[0009].[2021.04.03.01.17.14.855130].SRV1.INF:Main.py.<module>.313:AppSpoManager.DebugTargetFile=True
[0010].[2021.04.03.01.17.14.855631].SRV1.INF:Main.py.<module>.314:AppSpoManager.DebugTargetFilePath=Debugs\Debug1
[0011].[2021.04.03.01.17.14.856131].SRV1.INF:Main.py.<module>.315:AppSpoManager.DebugLinesPerFile=1000
[0012].[2021.04.03.01.17.14.856631].SRV1.INF:Main.py.<module>.316:AppSpoManager.AppRunFolder=c:\Apps\PythonTry1
[0013].[2021.04.03.01.17.14.857132].SRV1.INF:Main.py.<module>.339:ModuleFileNameOnly=Main.py
[0014].[2021.04.03.01.17.14.857632].SRV1.INF:Main.py.<module>.347:File=c:\Apps\PythonTry1\Main.py
[0015].[2021.04.03.01.17.14.858132].SRV1.INF:Main.py.<module>.348:FileDirName=c:\Apps\PythonTry1
[0016].[2021.04.03.01.17.14.858633].SRV1.INF:Main.py.<module>.349:FileAbsPath=c:\Apps\PythonTry1\Main.py
[0017].[2021.04.03.01.17.14.859133].SRV1.INF:Main.py.<module>.352:ModuleName1=__main__
[0018].[2021.04.03.01.17.14.859633].SRV1.INF:Main.py.<module>.353:ModuleName2=Main
[0019].[2021.04.03.01.17.14.860134].SRV1.INF:Main.py.<module>.362:Main Program Started
[0020].[2021.04.03.01.17.14.860634].SRV1.INF:Main.py.<module>.363:Python Executable Path=C:\Program Files\Python39\python.exe
[0021].[2021.04.03.01.17.14.861134].SRV1.INF:Main.py.<module>.364:Python Interpreter Version=3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
[0022].[2021.04.03.01.17.14.861635].SRV1.INF:Main.py.<module>.367:Sys.Path=['c:\\Apps\\PythonTry1', 'C:\\Program Files\\Python39\\python39.zip', 'C:\\Program Files\\Python39\\DLLs', 'C:\\Program Files\\Python39\\lib', 'C:\\Program Files\\Python39', 'C:\\Users\\user2\\AppData\\Roaming\\Python\\Python39\\site-packages', 'C:\\Program Files\\Python39\\lib\\site-packages']
[0023].[2021.04.03.01.17.14.893656].SRV1.INF:Main.py.<module>.414:Showing MainWindow
[0024].[2021.04.03.01.17.22.555920].SRV1.INF:Main.py.actionDebugTest1Handler.154:192.168.0.1, KAT1.ODA1, KORÝDOR DUVAR
192.168.0.2, KAT2.ODA2, TAVAN HOPARLÖR
192.168.0.3, KAT2.ODA2, KAPI_ÖNÜ_ANANS
